name: Check code quality with Python 3.13

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flake8-pyproject pytest mypy black isort

      - name: Lint with flake8
        run: |
          flake8 .
      - name: Lint with mypy
        run: |
          mypy .
      - name: Check style with isort
        run: |
          isort --check .
      - name: Check style with black
        run: |
          black --check .
